### ISSUE TITLE
The install script doesn't download the latest stable version of the ngrok agent

### ISSUE THREAD

**Issue by DominikPalo** [vincenthsu/systemd-ngrok#16]
The `install.sh` script downloads the ngrok agent from URL `https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-$ARCH.zip` - I'm not sure who manages that "mirror", but it doesn't point to the latest stable version of the ngrok agent: for example, it downloads v2.3.40 in case of the ARM64 architecture, although there are stable [v3 agents ](https://ngrok.com/docs/ngrok-agent/changelog) available for some time (e.g. https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-arm64.tgz)

**Comment by vincenthsu** [comment]
Updated, thanks.
