### ISSUE TITLE
Why git clone again in install.sh

### ISSUE THREAD

**Issue by rajanski** [vincenthsu/systemd-ngrok#6]
https://github.com/vincenthsu/systemd-ngrok/blob/master/install.sh#L13
doesnt make sense to me, since I assume I have the repo already cloned when executing install.sh

**Comment by JoaquimLey** [comment]
You could simply 
```
touch ngrok_install.sh
```

And then `nano` raw contents, also this would ensure you have the _latest_ version, not the one living on your machine.

This is just my $0.02 but better to wait for the maintainer's answer.

**Comment by JoaquimLey** [comment]
Hey @rajanski after seeing this issue and having to re-install multiple times on my raspis I decided to write a self-sufficient script so you don't need to re-clone:

### The whole package is open source here:
- https://github.com/JoaquimLey/ngrok-install

I've added detailed instructions in the `README.MD` file.

#### But you can simply copy-paste the raw script:
- https://raw.githubusercontent.com/JoaquimLey/ngrok-install/master/install.sh

**Comment by vincenthsu** [comment]
Hi @rajanski, 

Because I usually use the install.sh before cloning the repo:

```
curl -O  https://raw.githubusercontent.com/vincenthsu/systemd-ngrok/master/install.sh && chmod +x install.sh && sudo ./install.sh 
 <your_authtoken>
```

Thanks for your opinion. I will add  some condition to avoid double clones.
